name: Build on macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7' # Replace with the Ruby version used in your project

    - name: Build ams_lib.bundle
      run: |
        xcodebuild -project "${{ github.workspace }}/C++Extension/Projects/xCode/ams_lib.xcodeproj" -configuration Release
    
    - name: List Build Artifacts
      run: |
        ls -R "${{ github.workspace }}/DerivedData"
    
    - name: Find and Print ams_lib.bundle Location
      run: |
        find "${{ github.workspace }}" -name "ams_lib.bundle" -exec echo {} \;
